site_name: Blueprint
site_url: https://stephannv.github.io/blueprint-docs/
site_author: Stephann V.
site_description: >-
  Blueprint is a framework for writing reusable and testable HTML templates in
  plain Crystal, allowing an oriented object approach when building web views

copyright: Copyright &copy; 2023-present Stephann Vasconcelos

repo_name: stephannv/blueprint
repo_url: https://github.com/stephannv/blueprint

theme:
  name: material
  logo: assets/blueprint-logo.svg
  favicon: assets/favicon.ico
  features:
    - navigation.sections
    - navigation.instant
    - navigation.footer
    - navigation.tracking
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue
      toggle:
        icon: material/brightness-4
        name: Switch to system preference

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/stephannv/blueprint

nav:
  - index.md

  - Handbook:
    - handbook/getting-started.md
    - handbook/tags.md
    - handbook/attributes.md
    - handbook/utils.md
    - handbook/components.md
    - handbook/conditional-rendering.md
    - handbook/enveloping.md
    - handbook/helpers.md
    - handbook/forms.md
    - handbook/safety.md
    - handbook/style-variants.md
    - handbook/svg.md
    - handbook/builder.md
    - handbook/code-style.md


markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.superfences
  - admonition
  - pymdownx.details
